spring:
  datasource:
    master:
      url: jdbc:p6spy:mysql://112.74.46.153:12345/master
      username: root
      password: root
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    cluster:
        url: jdbc:p6spy:mysql://112.74.46.153:12345/cluster
        username: root
        password: root
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: top.liaoyichao.demo.entity
#  设置xml路径
#  mapper-locations:
logging:
  level:
    top.liaoyichao.demo.mapper: DEBUG
