spring:
  datasource:
      url: jdbc:p6spy:mysql://112.74.46.153:12345/my_test?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
mybatis:
  configuration:
    map-underscore-to-camel-case: true                # 开启驼峰命名
# config-location: classpath:mybatis/mybatis.cfg.xml    #  mybatis主配置文件所在路径
  # type-aliases-package: cn.lizheng.study.mybatis.pojo   #  定义实体类所在包
  # mapper-locations:                                     #  所有的mapper映射文件
  #  - classpath:mybatis/mapper/*.xml

pagehelper:
  helper-dialect: mysql
