#spring:
#  elasticsearch:
#    jest:
#      uris: http://112.74.46.153:9200
spring:
  data:
    elasticsearch:
#      节点名称 默认 elasticsearch
      cluster-name: elasticsearch
#      服务地址和端口
      cluster-nodes: 112.74.46.153:9301
