spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://112.74.46.153:12345/my_test
  redis:
    host: 112.74.46.153
    port: 6379
    password:
server:
  port: 8081
#mybatis:
#  type-aliases-package: top.liaoyichao.demo.entity
mapper:
  mappers: top.liaoyichao.demo.mapper
  identity: mysql
  not-empty: false
logging:
  level:
    top.liaoyichao.demo.mapper: debug